repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    -   id: flake8
        exclude: .templates/
-   repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
    -   id: xenon
        pass_filenames: false
        args: ["--max-average=A", "--max-modules=C", "--max-absolute=C", "endochrone"]